default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: prototyp_cal_development

production:
  adapter: mysql2
  encoding: utf8
  host: 51.68.137.244
  pool: 5
  database: prototyp_cal_production
  username: user
  password: Stabilox123
